apiVersion: v2
name: openawareness-controller
description: A Kubernetes operator for managing Grafana Mimir Prometheus Rules and Alertmanager configurations in a multi-tenant environment
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are expected to follow
# Semantic Versioning (https://semver.org/)
appVersion: "latest"

keywords:
  - kubernetes
  - operator
  - prometheus
  - grafana
  - mimir
  - alertmanager
  - monitoring
  - devops

home: https://github.com/Syndlex/Openawareness-Operator
sources:
  - https://github.com/Syndlex/Openawareness-Operator

maintainers:
  - name: Syndlex
    url: https://github.com/Syndlex
