# permissions for end users to edit clientconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openawareness-controller
    app.kubernetes.io/managed-by: kustomize
  name: openawareness-clientconfig-editor-role
rules:
- apiGroups:
  - openawareness.my.domain
  resources:
  - clientconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openawareness.my.domain
  resources:
  - clientconfigs/status
  verbs:
  - get
