# permissions for end users to view mimirtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openawareness-controller
    app.kubernetes.io/managed-by: kustomize
  name: openawareness-mimirtenant-viewer-role
rules:
- apiGroups:
  - openawareness.syndlex
  resources:
  - mimirtenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openawareness.syndlex
  resources:
  - mimirtenants/status
  verbs:
  - get
