# permissions for end users to edit mimirtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openawareness-controller
    app.kubernetes.io/managed-by: kustomize
  name: openawareness-mimirtenant-editor-role
rules:
- apiGroups:
  - openawareness.syndlex
  resources:
  - mimirtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openawareness.syndlex
  resources:
  - mimirtenants/status
  verbs:
  - get
