---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.coreos.com.syndlex
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com.syndlex
  resources:
  - prometheusrules/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.coreos.com.syndlex
  resources:
  - prometheusrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openawareness.syndlex
  resources:
  - clientconfigs
  - mimiralerttenants
  - mimirtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openawareness.syndlex
  resources:
  - clientconfigs/finalizers
  - mimiralerttenants/finalizers
  - mimirtenants/finalizers
  verbs:
  - update
- apiGroups:
  - openawareness.syndlex
  resources:
  - clientconfigs/status
  - mimiralerttenants/status
  - mimirtenants/status
  verbs:
  - get
  - patch
  - update
