apiVersion: openawareness.syndlex/v1beta1
kind: ClientConfig
metadata:
  name: clientconfig-sample
  labels:
    app.kubernetes.io/name: openawareness-controller
    app.kubernetes.io/component: client-config
    app.kubernetes.io/managed-by: kustomize
spec:
 address: "http://localhost:8080"
 type: mimir