---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: mimiralerttenants.openawareness.syndlex
spec:
  group: openawareness.syndlex
  names:
    kind: MimirAlertTenant
    listKind: MimirAlertTenantList
    plural: mimiralerttenants
    singular: mimiralerttenant
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: MimirAlertTenant is the Schema for the mimiralerttenants API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MimirAlertTenantSpec defines the desired state of MimirAlertTenant
            properties:
              alertmanagerConfig:
                description: |-
                  AlertmanagerConfig contains the raw Alertmanager configuration in YAML format
                  This should include global settings, routes, receivers, etc.
                type: string
              templateFiles:
                additionalProperties:
                  type: string
                description: |-
                  TemplateFiles contains Alertmanager notification templates
                  Key is the template name, value is the template content
                type: object
            required:
            - alertmanagerConfig
            type: object
          status:
            description: MimirAlertTenantStatus defines the observed state of MimirAlertTenant
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
